# Generated by Django 5.1 on 2024-10-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapi', '0002_roomparameters_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparameters',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomapi.room'),
        ),
    ]
