# Generated by Django 5.1 on 2024-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapi', '0004_rename_device_id_room_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
